### ISSUE TITLE
Lack of makefile...

### ISSUE THREAD

**Issue by fenrus75** [facebook/squangle#4]
There doesn't seem to be any sign of any makefile or related infrastructure....

**Comment by fredemmott** [comment]
This was released in an incomplete state so that it could be used by HHVM 3.6; it's fairly simple to build, and you can see how HHVM builds it here:

https://github.com/hhvm/hhvm-third-party/blob/master/squangle/CMakeLists.txt

The main thing you'd be likely to want to change is to not build a static library.

I'm trying to get this project owned as a standalone project instead of just a dependency, and this is definitely a priority once that happens.

**Comment by fenrus75** [comment]
well yeah we're trying to package HHVM for our distro, and the released
tarfile of it has no copy of squangle...
hence wanting to package this one ;-)

**Comment by fredemmott** [comment]
We don't make tarballs - and unfortunately github's automatic ones don't include submodules :(

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by fredemmott** [comment]
no thanks FBBot.

**Comment by yggchan** [comment]
Any updates on this ?

**Comment by SharpMan** [comment]
They won't they don't care. They are just saying 'Hi we have a mysql async client library !'
especially when this quality of code https://github.com/facebook/squangle/blob/master/squangle/mysql_client/Query.cpp#L236
doesn't need to go in production

**Comment by fredemmott** [comment]
Closing all issues and moving to facebookarchive; this is still supported as a dependency of HHVM, but not as a standalone project.
